name: 'Disable Devovorga pack'

on:
  schedule:
    # Run annually at 04:00 UTC on October 1st.
    - cron: '0 4 1 10 *'
  workflow_dispatch:

jobs:
  disable-lightbearer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Disable pack
        run: |
          node scripts/disable-marker-pack.mjs devovorga
          git config user.name 'TibiaMaps.io'
          git config user.email 'ci@tibiamaps.io'
          git commit data -m 'Disable Devovorga pack' -m 'This patch disables the Rise of Devovorga markers now that the event (which runs from September 1st until September 7th, with potential rewards until October 1st) has come to an end.'
          git push
